config/routes.rb
Rails.application.routes.draw do
  

  resources :rooms
  #get 'pings/home'
  #post 'assigns/create'
  post 'rooms/sessions'
  resources :chatrooms do 
  		resource :chatroom_users
  		resources :messages
  end
  devise_for :users
  root 'chatrooms#index'
  get 'audio'=> "audios#home"
  get "page" => "pages#home"
  get "ping" => "pings#home"
 resources :assigns
 resources :pings
 resources :periods
 resources :direct_messages
 resources :audios
  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :chatroom_users, dependent: :destroy
  has_many :users, through: :chatroom_users
  has_many :messages, dependent: :destroy

  scope :public_channels, ->{ where(direct_message: false) }
  scope :direct_messages, ->{ where(direct_message: true) }

  def self.direct_message_for_users(users)
    user_ids = users.map(&:id).sort
    name = "DM:#{user_ids.join(":")}"

    if chatroom = direct_messages.where(name: name).first
      chatroom
    else
      # create a new chatroom
      chatroom = new(name: name, direct_message: true)
      chatroom.users = users
      chatroom.save
      chatroom
    end
  end
end

app/models/chatroom_user.rb
class ChatroomUser < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
  before_create :set_last_read

  def set_last_read
    self.last_read_at = Time.zone.now
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord
	extend FriendlyId
	friendly_id :roomname, use: :slugged
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  has_many :chatroom_users
  has_many :chatrooms, through: :chatroom_users
  has_many :messages
end

app/controllers/assigns_controller.rb
class AssignsController < ApplicationController
  def create
    head :no_content
    ActionCable.server.broadcast "session_channel", params
  end
end

app/controllers/audios_controller.rb
require 'rest-client'
require 'json'
class AudiosController < ApplicationController
  def home

    @random_number = rand(0...10_000)

    response = RestClient.put "https://ravirey04:4b49a0f8-ad9a-11e7-a387-084a2cfd4227@global.xirsys.net/_turn/railswebrtc", accept: :json
    @json_response = response.to_json

  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :set_chatroom, only: [:show, :edit, :update, :destroy]

  # GET /chatrooms
  # GET /chatrooms.json
  def index
    @chatrooms = Chatroom.public_channels
  end

  # GET /chatrooms/1
  # GET /chatrooms/1.json
  def show
  
    @chatroom_user = current_user.chatroom_users.find_by(chatroom_id: @chatroom.id)
    @messages = @chatroom.messages.order(created_at: :desc).limit(100).reverse
  end

  # GET /chatrooms/new
  def new
    @chatroom = Chatroom.new
  end

  # GET /chatrooms/1/edit
  def edit
  end

  # POST /chatrooms
  # POST /chatrooms.json
  def create
    @chatroom = Chatroom.new(chatroom_params)
  if @chatroom.save
        @chatroom.chatroom_users.where(user_id: current_user.id).first_or_create
        #format.html { redirect_to @chatroom, notice: 'Chatroom was successfully created.' }
        #format.json { render :show, status: :created, location: @chatroom }
  redirect_to @chatroom 
      else
        format.html { render :new }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end

  end

  # PATCH/PUT /chatrooms/1
  # PATCH/PUT /chatrooms/1.json
  def update
    respond_to do |format|
      if @chatroom.update(chatroom_params)
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @chatroom }
      else
        format.html { render :edit }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chatrooms/1
  # DELETE /chatrooms/1.json
  def destroy
    @chatroom.destroy
    respond_to do |format|
      format.html { redirect_to chatrooms_url, notice: 'Chatroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chatroom
      @chatroom = Chatroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chatroom_params
      params.require(:chatroom).permit(:name)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # before_action :set_chatroom

  # def create
  #   message = @chatroom.messages.new(message_params)
  #   message.user = current_user
  #   message.save
  #   MessageRelayJob.perform_later(message)
  # end

  # private

  #   def set_chatroom
  #     @chatroom = Chatroom.find(params[:chatroom_id])
  #   end

  #   def message_params
  #     params.require(:message).permit(:body)
  #   end
end

app/controllers/periods_controller.rb
class PeriodsController < ApplicationController
def create
    head :no_content
    ActionCable.server.broadcast "period_channel", params
 end
end

app/controllers/pings_controller.rb
require 'rest-client'
require 'json'

class PingsController < ApplicationController
  def home
    #@rand_number = rand(0...10_000)
	response = RestClient.put "https://ravirey04:4b49a0f8-ad9a-11e7-a387-084a2cfd4227@global.xirsys.net/_turn/railswebrtc", accept: :json
    @json_res = response.to_json
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  def index
    $rooms = Room.all
  end


  def show
    @random_number = rand(0...10_000)
    response = RestClient.put "https://ravirey04:4b49a0f8-ad9a-11e7-a387-084a2cfd4227@global.xirsys.net/_turn/railswebrtc", accept: :json
    @json_response = response.to_json
  end


  def new
    $room = Room.new
  end


  def create
    $room = Room.new(room_params)

    respond_to do |format|
      if $room.save
        format.html { redirect_to $room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: $room }
      else
        format.html { render :new }
        format.json { render json: $room.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    $room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
   def sessions
      head :no_content
      ActionCable.server.broadcast "dummy_channel_#{$room.roomname}", params
     # Rails.logger.debug "qwertyyuuu:#{$room.roomname}"
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      $room = Room.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:roomname)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assigns_helper.rb
module AssignsHelper
end

app/helpers/audios_helper.rb
module AudiosHelper
end

app/helpers/chatroom_users_helper.rb
module ChatroomUsersHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/direct_messages_helper.rb
module DirectMessagesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/pings_helper.rb
module PingsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/chatrooms/_form.html.erb
<%= form_for(chatroom) do |f| %>
  <% if chatroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chatroom.errors.count, "error") %> prohibited this chatroom from being saved:</h2>

      <ul>
      <% chatroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chatrooms/edit.html.erb
<h1>Editing Chatroom</h1>

<%= render 'form', chatroom: @chatroom %>

<%= link_to 'Show', @chatroom %> |
<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chatrooms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chatrooms.each do |chatroom| %>
      <tr>
        <td><%= chatroom.name %></td>
        <td><%= link_to 'Show', chatroom %></td>
        <td><%= link_to 'Edit', edit_chatroom_path(chatroom) %></td>
        <td><%= link_to 'Destroy', chatroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to "Join", chatroom_chatroom_users_path(chatroom), method: :post %></td>
        <td><%= link_to "Leave", chatroom_chatroom_users_path(chatroom), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chatroom', new_chatroom_path %>

app/views/chatrooms/new.html.erb
<h1>New Chatroom</h1>

<%= render 'form', chatroom: @chatroom %>

<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @chatroom.name %>
</p>

<% unread_messages = false %>
<div data-behavior='messages' data-chatroom-id='<%= @chatroom.id %>'>
  <% @messages.each do |message| %>
    <% if !unread_messages && @chatroom_user.last_read_at < message.created_at %>
      <% unread_messages = true %>
      <div class="strike"><span>Unread Messages</span></div>
    <% end %>

    <%= render message %>
  <% end %>
</div>

<%= form_for [@chatroom, Message.new] do |f| %>
  <%= f.text_area :body, rows: 1, class: "form-control", autofocus: true %>
<% end %>

app/views/messages/_message.html.erb
<div><strong><%= message.user.username%>:</strong> <%= message.body %></div>

app/views/messages/create.js.erb
$("#new_message")[0].reset()

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div id = "displayText"></div>

  <div class="field">
    <%= form.label :roomname %>
    <%= form.text_field :roomname, id: :room_roomname %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>



<% content_for :page_js do %>
  <script type="text/javascript">

  var inputBox = document.getElementById('room_roomname');

  inputBox.onkeyup = function(){
    
    inputText()
}

function inputText() {
  if (inputBox.value === "") {

    document.getElementById('displayText').innerHTML = "";
  }

  else {
    inputBox.value=inputBox.value.replace(/ /g,"-");

    document.getElementById('displayText').innerHTML = "https://rtcping.herokuapp.com/rooms/"+ inputBox.value;
  }
}
  </script>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Roomname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% $rooms.each do |room| %>
      <tr>
        <td><%= room.roomname %></td>
        <td><%= link_to 'Join Room', room , method: :get %></td>
        <td> |  | </td>
        <td><%= link_to 'Delete Room', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: $room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>
<div id = "roomname" data-roomname = '<%= $room.roomname %>'>
  <p>
  <strong>Roomname:</strong>
  <%= $room.roomname %>
</p>
</div>
<div>
  <%= text_field_tag :room ,  "https://rtcping.herokuapp.com/rooms/#{$room.slug}" %>
  <button type="button" id="copy">copy me</button>
</div>

<h1>Action Cable Signaling Server</h1>

<span id="xirsys-creds" data-xirsys='<%= @json_response.html_safe %>'>
</span> 

<div>Random User ID:
  <span id="currentUser" class="badge badge-primary"><%= @random_number %></span>
</div>

<div id="remoteViewContainer"></div>

<div class="row">
  <div class="col-md-12">
    <div id="localViewContainer">
      <video id="selfView" autoplay></video>
    </div>
  </div>
</div>

<div id="join-btn-container">
  <button onclick="handleJoinSession()" class="btn btn-success">
    Join Room
  </button>
</div>

<div id="leave-btn-container">
  <button onclick="handleLeaveSession()" class="btn btn-danger">
    Leave Room
  </button>
</div>



<% content_for :page_js do %>
  <script type="text/javascript">
    <%= render file: "#{Rails.root}/app/views/rooms/js/roomwebrtc.js" %>
  </script>
<% end %>