config/routes.rb
Rails.application.routes.draw do
  

  resources :rooms
  #get 'pings/home'
  #post 'assigns/create'
  post 'rooms/sessions'
  resources :chatrooms do 
  		resource :chatroom_users
  		resources :messages
  end
  devise_for :users
  root 'chatrooms#index'
  get 'audio'=> "audios#home"
  get "page" => "pages#home"
  get "ping" => "pings#home"
 resources :assigns
 resources :pings
 resources :periods
 resources :direct_messages
 resources :audios
  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :chatroom_users, dependent: :destroy
  has_many :users, through: :chatroom_users
  has_many :messages, dependent: :destroy

  scope :public_channels, ->{ where(direct_message: false) }
  scope :direct_messages, ->{ where(direct_message: true) }

  def self.direct_message_for_users(users)
    user_ids = users.map(&:id).sort
    name = "DM:#{user_ids.join(":")}"

    if chatroom = direct_messages.where(name: name).first
      chatroom
    else
      # create a new chatroom
      chatroom = new(name: name, direct_message: true)
      chatroom.users = users
      chatroom.save
      chatroom
    end
  end
end

app/models/chatroom_user.rb
class ChatroomUser < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
  before_create :set_last_read

  def set_last_read
    self.last_read_at = Time.zone.now
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord
	extend FriendlyId
	friendly_id :roomname, use: :slugged
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  has_many :chatroom_users
  has_many :chatrooms, through: :chatroom_users
  has_many :messages
end

app/controllers/assigns_controller.rb
class AssignsController < ApplicationController
  def create
    head :no_content
    ActionCable.server.broadcast "session_channel", params
  end
end

app/controllers/audios_controller.rb
require 'rest-client'
require 'json'
class AudiosController < ApplicationController
  def home

    @random_number = rand(0...10_000)

    response = RestClient.put "https://ravirey04:4b49a0f8-ad9a-11e7-a387-084a2cfd4227@global.xirsys.net/_turn/railswebrtc", accept: :json
    @json_response = response.to_json

  end
end

app/controllers/periods_controller.rb
class PeriodsController < ApplicationController
def create
    head :no_content
    ActionCable.server.broadcast "period_channel", params
 end
end

app/controllers/pings_controller.rb
require 'rest-client'
require 'json'

class PingsController < ApplicationController
  def home
    #@rand_number = rand(0...10_000)
	response = RestClient.put "https://ravirey04:4b49a0f8-ad9a-11e7-a387-084a2cfd4227@global.xirsys.net/_turn/railswebrtc", accept: :json
    @json_res = response.to_json
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  def index
    $rooms = Room.all
  end


  def show
    @random_number = rand(0...10_000)
    response = RestClient.put "https://ravirey04:4b49a0f8-ad9a-11e7-a387-084a2cfd4227@global.xirsys.net/_turn/railswebrtc", accept: :json
    @json_response = response.to_json
  end


  def new
    $room = Room.new
  end


  def create
    $room = Room.new(room_params)

    respond_to do |format|
      if $room.save
        format.html { redirect_to $room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: $room }
      else
        format.html { render :new }
        format.json { render json: $room.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    $room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
   def sessions
      head :no_content
      ActionCable.server.broadcast "dummy_channel_#{$room.roomname}", params
     # Rails.logger.debug "qwertyyuuu:#{$room.roomname}"
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      $room = Room.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:roomname)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assigns_helper.rb
module AssignsHelper
end

app/helpers/audios_helper.rb
module AudiosHelper
end

app/helpers/chatroom_users_helper.rb
module ChatroomUsersHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/pings_helper.rb
module PingsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebRTC on Rails</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'application/favicon' %>
  </head>

  <body>
   <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: "navbar-brand" do %>
            Chat
          <% end %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <%= yield :right_nav %>

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Settings", edit_user_registration_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="fluid-container" style="margin-top: 70px">
      <div class = "row">
        <div class = "col-sm-2" style="position: fixed; top: 70px; left: 0;">
        <% if user_signed_in? %>
        <h3> Chatroom</h3>
            <ul>
              <% current_user.chatrooms.public_channels.each do |chatroom| %>
                <li><%= link_to chatroom.name, chatroom, data:{ behavior: "chatroom-link", chatroom_id:chatroom.id } %></li>
              <% end %>
            </ul>
            
            <h5>Users</h5>
            <ul>
              <% (User.all - [current_user]).each do |user| %>
                <li><%= link_to user.username, direct_message_path(user.id), data: {behavior: "chatroom-link", chatroom_id: Chatroom.direct_message_for_users([current_user, user]).id } %></li>
              <% end %>
            </ul>
         
        </div>

        <% end %>

          
        </div>
        <div class= "col-sm-10 col-sm-offset-2"">
      <%= yield %>
      </div>
    </div>
    </div>
    <%= yield :page_js %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-toggleable-xl navbar-light">
  <a class="navbar-brand">
    <%= image_tag("logo.svg", size: "30", alt: "WebRTC on Rails", class: "img-fluid") %>
  </a>
  </ul>
</nav>